#!/bin/sh

# This sets up your new repos with mr.

cat > $HOME/.config/mr/available.d/$HOMEROOMS_DIRECTORY.room << EOF
[\$HOME/.config/house/rooms/$HOMEROOMS_DIRECTORY.git]
checkout = room clone $GITURL/dotfiles/$HOMEROOMS_DIRECTORY.git
EOF

ln -s $HOME/.config/mr/available.d/$HOMEROOMS_DIRECTORY.room $HOME/.config/mr/config.d/
