#!/bin/sh

# This finds objects that the pre-merge script moved out of the way to
# avoid conflicts when running `nook clone` and moves them back to their
# original places. The result is that the Git repository gets checked out
# without error and the pre-existing files end up back in the working
# directory. Git and thus nook now see these as un-staged changes to the
# working branch and you can deal with them as usual.

find . -name '*.nook-unclobber' -execdir rename .nook-unclobber '' {} \;
