#!/bin/sh

# This sets up your new repos with mr.

cat > $HOME/.config/mr/available.d/$HOUSEROOM_DIRECTORY.room << EOF
[\$HOME/.config/house/rooms/$HOUSEROOM_DIRECTORY.git]
checkout = room clone $GITURL/dotfiles/$HOUSEROOM_DIRECTORY.git
EOF

ln -s $HOME/.config/mr/available.d/$HOUSEROOM_DIRECTORY.room $HOME/.config/mr/config.d/
